### ISSUE TITLE
Put quotes around scope variable values that are strings on 500 page

### ISSUE THREAD

**Issue by errieman** [stefvanhouten/uweb3#27]
Currently it is difficult to see whether a variable value is a string or another type on the 500 page. So it would be nice to be able to see the type of a variable or at least whether it is a string or not.

How to reproduce:
Trigger a 500 error on a DebuggingPageMaker and look at the scope-variables.

Expected:
```
string_var (str) = "1"
int_var (int) = 1
```
or:
```
string_var = "1"
int_var = 1
```

Actual:
```
string_var = 1
int_var = 1
```

**Comment by stefvanhouten** [comment]
Added.
